import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import BioComp from '../components/Bio_block/BioComp'

export default function BioPage() {
  return (
    <div>
      <Head>
        <title>Bio |Tech-Portfolio</title>
        <meta name="description" content="Generated by TheLastGoodMan" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.container}>
        <h1>Bio Page</h1>
        <BioComp />
      </main>

      
    </div>
  )
}
