import Head from 'next/head'
import styles from '../styles/Home.module.scss'

export default function GithubPage() {
  return (
    <div>
      <Head>
        <title>Github |Tech-Portfolio</title>
        <meta name="description" content="Generated by TheLastGoodMan" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.container}>
        <h1>Github Page</h1>
      </main>

      
    </div>
  )
}
