import Head from 'next/head';
import styled from 'styled-components';
// import DisplayAreaLayoutComp from '../components/Layout/DisplayAreaLayout';
import HomePageLayout from '../components/Layout/HomePageLayout';
import CodeLinesComp from '../components/codelines/CodeLinesComp';
import WelcomeComp from '../components/Welcome/Welcome';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Home |Tech-Portfolio</title>
        <meta name="description" content="Generated by TheLastGoodMan" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      {/* <DisplayAreaLayoutComp>
        <>
          <CodeLinesComp />
          <h1>Home Page</h1>
        </>
      </DisplayAreaLayoutComp> */}
      <HomePageLayout>
        <>
          <CodeLinesComp />
          <WelcomeComp />
        </>
      </HomePageLayout>

      
    </div>
  )
};


//styled components for HomePage 
`

// const HomePageHeading1 = styled.h1`
//     font-size: 1rem;
// `


