import Head from 'next/head';
import styled from 'styled-components';
import TabsLayoutComp from '../components/Layout/TabsLayout';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Home |Tech-Portfolio</title>
        <meta name="description" content="Generated by TheLastGoodMan" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HomePageContainer>
        <TabsLayoutComp />
            <h1>Home Page</h1>
      </HomePageContainer>

      
    </div>
  )
};


//styled components for HomePage

const HomePageContainer = styled.main`
    max-height: 100vh;
    padding: 0 0.5rem;
    width: 100%;
    margin: 20px auto;
    overflow: hidden;
`

// const HomePageHeading1 = styled.h1`
//     font-size: 1rem;
// `


