import Head from 'next/head';
import ProjectComp from '../components/Project/ProjectComp';
import DisplayAreaLayoutComp from '../components/Layout/DisplayAreaLayout';
import CodeLinesComp from '../components/codelines/CodeLinesComp';
import {PageLayout} from '../components/Layout/PageLayout';
import styled from 'styled-components';

export default function ProjectPage() {
  return (
    <div>
      <Head>
        <title>Projects |Tech-Portfolio</title>
        <meta name="description" content="Generated by TheLastGoodMan" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <DisplayAreaLayoutComp pagepath='pages' filename='projects.jsx' filename_icon='reactIcon'>  
          <StyledMain>
            <PageLayout>
              <CodeLinesComp />
              <ProjectComp />
            </PageLayout>
    
            <PageLayout>
              <CodeLinesComp />
              <ProjectComp />
            </PageLayout>
          </StyledMain>
      </DisplayAreaLayoutComp>
      
    </div>
  )
};

const StyledMain = styled.main`
    display: flex;
`


