import Head from 'next/head';
import styles from '../styles/Home.module.scss';
import ProjectComp from '../components/Project/ProjectComp';
import DisplayAreaLayoutComp from '../components/Layout/DisplayAreaLayout';
import CodeLinesComp from '../components/codelines/CodeLinesComp';

export default function ProjectPage() {
  return (
    <div>
      <Head>
        <title>Projects |Tech-Portfolio</title>
        <meta name="description" content="Generated by TheLastGoodMan" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <DisplayAreaLayoutComp>
        <>
          <CodeLinesComp />
          <h1>Projects Page</h1>
           <ProjectComp />
        </>
      </DisplayAreaLayoutComp>
      
    </div>
  )
};



