import Head from 'next/head'
import styled from 'styled-components';


export default function CodebasePage() {
  return (
    <div>
      <Head>
        <title>Code Base |Tech-Portfolio</title>
        <meta name="description" content="Generated by TheLastGoodMan" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HomePageContainer>
        <h1> CodeBase Page </h1>
      </HomePageContainer>

      
    </div>
  )
};


//styled components for ContactMe Page

const HomePageContainer = styled.main`
    max-height: 100vh;
    padding: 0 0.5rem;
    width: 100%;
    margin: 20px auto;
    overflow: hidden;
`



