import Head from "next/head";
import DisplayAreaLayoutComp from "../components/Layout/DisplayAreaLayout";
import CodeLinesComp from "../components/codelines/CodeLinesComp";
import FormComp from "../components/Form/FormComp";
import { PageLayout } from "../components/Layout/PageLayout";
import styled from "styled-components";
import { useContext } from "react";
import { CalculateHeightContext } from "../context/index";
import { mediaQueries } from "../components/common/breakpoints";

export default function ContactPage() {
  const { elementRef } = useContext(CalculateHeightContext);

  return (
    <div>
      <Head>
        <title>Contact | Tech-Portfolio</title>
        <meta name="description" content="Generated by TheLastGoodMan" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <DisplayAreaLayoutComp
        pagepath="pages"
        filename="contact.js"
        filename_icon="javaScriptIcon"
      >
        <>
          <PageLayout>
            <CodeLinesComp />
            <StyledDiv ref={elementRef}>
              <StyledSection>
                <h2>
                  <span>Get in Touch...</span>
                </h2>
                <p>Any question, feedback or remarks?</p>
                <p>Feel free to drop me a message!</p>
              </StyledSection>
              <FormComp />
            </StyledDiv>
          </PageLayout>
        </>
      </DisplayAreaLayoutComp>
    </div>
  );
}

const StyledDiv = styled.div`
  width: 100%;
  display: flex;
  align-items: center;
  justify-content: center;
  background-color: #000;
  /* height: 100%; */
  height: 80vh;

  ${mediaQueries("mobileM")`
      display: block;
      height: 100vh;
  `}
`;

const StyledSection = styled.section`
  margin-right: 4rem;
  /* border: 1px solid; */
  padding: 0.7rem;

  ${mediaQueries("mobileM")`
        margin: 5px 0px;
        text-align: center;
  `}

  h2 {
    font-size: 2.5rem;
    font-weight: 700;
    color: #d9dddc;
    letter-spacing: 3px;

    ${mediaQueries("mobileM")`
        font-size: 1.7rem;
        color: green;
        letter-spacing: 2px;
  `}
  }

  p {
    font-size: 0.9rem;
    letter-spacing: 1.3px;
    color: #eee;
    padding-left: 5px;
  }
`;
