import Head from "next/head";
import Image from "next/image";
import styled from "styled-components";
// import DisplayAreaLayoutComp from '../components/Layout/DisplayAreaLayout';
import HomePageLayout from "../components/Layout/HomePageLayout";
import CodeLinesComp from "../components/codelines/CodeLinesComp";
import { useContext } from "react";
import { CalculateHeightContext } from "../context/index";
import { ColorThemeDisplay } from "../components/Form/CustomModal";
// import FilepathComp from '../components/filepath/Filepath';

export default function Dummy() {
  const { elementRef } = useContext(CalculateHeightContext);

  return (
    <div>
      <Head>
        <title>Dummy |Tech-Portfolio</title>
        <meta name="description" content="Generated by TheLastGoodMan" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <DisplayAreaLayoutComp>
        <>
          <CodeLinesComp />
          <h1>Home Page</h1>
        </>
      </DisplayAreaLayoutComp> */}
      <HomePageLayout>
        <StyledDiv ref={elementRef}>
          <CodeLinesComp />
          <ColorThemeDisplay />
        </StyledDiv>
      </HomePageLayout>
    </div>
  );
}

//styled components for HomePage

const StyledDiv = styled.div`
  height: 100%;
  width: 100%;
  display: flex;
  /* align-items: center; */
  /* justify-content: center; */
`;
