import Head from "next/head";
// import WelcomeComp from '../components/Welcome/Welcome'
import styled from "styled-components";

export default function GithubPage() {
  return (
    <div>
      <Head>
        <title>Git-connect |Tech-Portfolio</title>
        <meta name="description" content="Generated by TheLastGoodMan" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HomePageContainer>
        <h1> GithubConnect Page </h1>
      </HomePageContainer>
    </div>
  );
}

//styled components for ContactMe Page

const HomePageContainer = styled.main`
  max-height: 100vh;
  padding: 0 0.5rem;
  width: 100%;
  margin: 20px auto;
  overflow: hidden;
`;
