import Head from "next/head";
// import ProjectComp from '../components/Project/ProjectComp';
import {
  ProjectCollectionTwo,
  ProjectCollectionOne,
} from "../components/Project/ProjectComp";
import DisplayAreaLayoutComp from "../components/Layout/DisplayAreaLayout";
import CodeLinesComp from "../components/codelines/CodeLinesComp";
import { PageLayout } from "../components/Layout/PageLayout";
import styled from "styled-components";
import { mediaQueries } from "../components/common/breakpoints";

export default function ProjectPage() {
  return (
    <div>
      <Head>
        <title>Projects | Tech-Portfolio</title>
        <meta name="description" content="Generated by TheLastGoodMan" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <DisplayAreaLayoutComp
        pagepath="pages"
        filename="projects.jsx"
        filename_icon="reactIcon"
      >
        <StyledMain>
          <PageLayout>
            <CodeLinesComp />
            <ProjectCollectionOne />
          </PageLayout>

          <PageLayout>
            <CodeLinesComp />
            <ProjectCollectionTwo />
          </PageLayout>
        </StyledMain>
      </DisplayAreaLayoutComp>
    </div>
  );
}

const StyledMain = styled.main`
  display: flex;

  ${mediaQueries("mobileL")`
      flex-direction: column;
  `}
  ${mediaQueries("mobileM")`
      flex-direction: column;
  `}
`;
